# ~/.config/fuzzel/fuzzel.ini

[main]
font=JetBrainsMono Nerd Font Propo:weight=bold:size=12
icon-theme=Adwaita
terminal=alacritty -e
layer=overlay
width=40
lines=8
horizontal-pad=24
vertical-pad=16
inner-pad=10
line-height=26

# скрывает приложения, у которых OnlyShowIn/NotShowIn не совпадает с текущим DE
# полезно, если .desktop файл помечен как специфичный для GNOME/KDE
filter-desktop=yes

[colors]
# формат: RRGGBBAA, без 0x
background=121318e6
text=e2e2e9ff
match=b0c6ffff
selection=2e4578ff
selection-text=d9e2ffff
selection-match=b0c6ffff
border=b0c6ffaa

[border]
width=2
radius=20

[dmenu]
exit-immediately-if-empty=yes
