format = """
[](fg:@base01@)\
[  $directory](bg:@base01@ fg:@base05@)\
[](fg:@base01@ bg:@base02@)\
[  $git_branch$git_status](bg:@base02@ fg:@base0A@)\
[](fg:@base02@)
$character"""

[directory]
style = "bg:@base02@ fg:@base05@"

[git_branch]
symbol = " "
style = "bg:@base03@ fg:@base04@"

[git_status]
style = "bg:@base03@ fg:@base08@"

[character]
success_symbol = "[❯](bold @base0D@)"
error_symbol = "[❯](bold @base08@)"
vicmd_symbol = "[❮](bold @base0E@)"

[cmd_duration]
min_time = 2000
format = "[took $duration ](fg:#8f9099)"
