# ~/.config/foot/foot.ini
# Палитра — Matugen-тема, та же что в waybar/colors.css и alacritty.toml

[main]
font=JetBrainsMono Nerd Font Mono:size=11
# font-size-adjustment=10px
resize-by-cells=no
pad=12x10 center
# dpi-aware=yes

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[colors-dark]
alpha=0.92

background=121318
foreground=e2e2e9

selection-background=404659
selection-foreground=d9e2ff

# normal (0-7)
regular0=121318
regular1=ffb4ab
regular2=b0c6ff
regular3=c0c6dc
regular4=475d91
regular5=e0bbde
regular6=a6c8ff
regular7=c5c6d0

# bright (8-15)
bright0=44464f
bright1=ffdad6
bright2=d9e2ff
bright3=dce2f9
bright4=b0c6ff
bright5=fdd7fa
bright6=c9d5f9
bright7=e2e2e9

[scrollback]
lines=10000

[url]
launch=xdg-open ${url}

[csd]
preferred=none
size=0
