[[mgr.prepend_keymap]]
on = "U"
run = 'shell -- echo worked > /tmp/yazi-shell-test'
desc = "Test shell"

[[mgr.prepend_keymap]]
on = "e"
run = 'shell --block -- gdu %s'
desc = "Размер папки"

[[mgr.prepend_keymap]]
on = "y"
run = [
    'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list',
    "yank"
]
desc = "Yank как URI"

