[[mgr.prepend_keymap]]
on = "e"
run = 'shell --block -- gdu %s'
desc = "Интерактивно посмотреть размер папок (gdu)"

[[mgr.prepend_keymap]]
on = "y"
run = [
    'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list',
    "yank"
]
desc = "Yank как URI"
